### ISSUE TITLE
DIC Setup not working correctly, 

### ISSUE THREAD

**Issue by zemorango** [RRUZ/delphi-ide-theme-editor#100]
Hi, when I install DIC IDE, there is no executable file beside the uploader.exe in the directory
C:\Users\zemor\AppData\Local\The Road To Delphi\DIC\XE8  , there is no program installed in, so what's wrong ?

**Comment by RRUZ** [comment]
This is the issue page of the _Delphi IDE Theme Editor_ project. To report the issues of the DIC plugin  you must use this another page https://github.com/RRUZ/Delphi-IDE-Colorizer/issues
