### ISSUE TITLE
DITE not recognizing Delphi 10 installed

### ISSUE THREAD

**Issue by havanamike** [RRUZ/delphi-ide-theme-editor#104]
See attachment...
![image_20160412_1](https://cloud.githubusercontent.com/assets/809052/14470709/ad39dfdc-00b0-11e6-897e-a35aa95352b9.jpg)
Not sure if this is an issue with the application being able to read the registry or not. I get the error even if I run as administrator.

Windows Server 2012 R2

**Comment by RRUZ** [comment]
Are you using the last version of DITE 1.87.1.0 ?

**Comment by havanamike** [comment]
When I click the link for Installer of the Delphi IDE Theme Editor - Mirror 2 from https://github.com/RRUZ/delphi-ide-theme-editor, the details show it as 1.7.1. Does that link not point to the lastest release?

I cannot download from dropbox at work, so I am dependent on the Mirror 2 link.

**Comment by RRUZ** [comment]
Hi, the mirror 2 link was updated. Try again

**Comment by havanamike** [comment]
Thanks for link. DITE now finds Delphi 10
