### ISSUE TITLE
IDE Theme editor installs its themes into the "wrong" location

### ISSUE THREAD

**Issue by luebbe** [RRUZ/delphi-ide-theme-editor#105]
At the company we have to install DITE with a separate admin account instead of the user account. Unfortunately it installs its themes and/or its config into this admin users appdata folder and becomes unusable for normal users this way.
If you start DITE as a normal user afterwards, the application looks like in the attached screenshot after showing an error message "Style 'xxx' not found".
It does not help to copy the themes folder to the normal users DITE themes folder.

![2016-04-21 15_50_27-delphi ide theme editor](https://cloud.githubusercontent.com/assets/3872576/14711226/d175b392-07d8-11e6-8d08-9512adcfe83d.png)

**Comment by RRUZ** [comment]
Hi, I just fixed this issue. Please try the new version 1.90.4.30

**Comment by luebbe** [comment]
Sorry, no visible improvement for me. The error message and the screen are exactly the same with 1.90.4.30.
Do I have to delete some registry keys/files before installing to get to a clean setup? Does the new version still look for its files and config in "old" places to be backwards compatible?
Do you check the "common" location first and the "private" second if nothing is found in the "common" location or the other way round?
Just ideas what could be happening.

**Comment by RRUZ** [comment]
The new version was tested following these steps :

1. Uninstall any previous version using an _admin _account
2. Delete the file _%appdata%\DITE\Settings.ini_ for each user.
3. Install the new version (1.90.4.30) using the _admin _account
4. DITE detects the installed RAD Studio versions checking this key _HKEY_CURRENT_USER\Software\Embarcadero\BDS\nn_, So before to run DITE under the _normal _ accounts be sure that RAD Studio was executed previously at least once and /or  check if the proper registry keys exists under the current user.
5. Now you can Run DITE  using the _normal_ or _admin_ accounts.

  Notes :

  1. The Themes (and all the common files) now are stored in the _CSIDL_COMMON_APPDATA_ Folder.
  2. The installer of DITE modify the ACL of the child folders of _CSIDL_COMMON_APPDATA\DITE_ to allow to the normal user access to such folders.

Please let me know the results.

If the issue persist please send me a image of the exception _"Style 'xxx' not found"._ or any other exception message.

**Comment by luebbe** [comment]
Thanks Rodrigo, the issue is solved.
The "style 'xxx' not found" showed a style name "Metro Blue" that isn't included in DITE anymore.

This was my settings.ini:
```
[Global]
ThemePath=C:\Users\<xxx>\AppData\Roaming\DITE\Themes
VCLStyle=Metro Blue
CheckForUpdates=1
ApplyThemeHelpInsight=0
```

There was no DITE\settings.ini in the _admin_ users %appdata% folder after uninstalling, just the DITE\Themes folder.
Is it possible that the non-exisiting style threw DITE off course?

**Comment by RRUZ** [comment]
Thanks for your feedback, the next version will include a validation to prevent this issue when a  _VCL Style_ is not found.
