### ISSUE TITLE
Windows registry

### ISSUE THREAD

**Issue by charoleizer** [RRUZ/delphi-ide-theme-editor#107]
Is there a way to choose the theme for specific registry on windows ?
When i apply the theme, it'll be apply on main registry: ..\Embarcadero\BDS\17.0\..
but i want theme applied here: ..\Embarcadero\Trunk\17.0\..

**Comment by RRUZ** [comment]
Hi, I just added the detection of custom registry keys for RAD Studio, try the new version 1.90.5.10

**Comment by charoleizer** [comment]
It's perfect now. Thanks
