### ISSUE TITLE
Some style issues

### ISSUE THREAD

**Issue by 0x92** [RRUZ/delphi-ide-theme-editor#108]
I uninstalled the theme editor but there is still one thing which seems like which is not removed correctly. How can i fix it / take the default settings?

![hvh0vtf](https://cloud.githubusercontent.com/assets/6593435/14953990/fa6ac15e-106e-11e6-9b5c-100681f8a2fb.png)

**Comment by RRUZ** [comment]
Are sure which this report is about [DITE](https://github.com/RRUZ/delphi-ide-theme-editor) and not about the  [DIC](https://github.com/RRUZ/Delphi-IDE-Colorizer) project?

**Comment by 0x92** [comment]
Well im not 100% sure because i installed both and uninstalled both now. If its the DITE can yo utell me how do i reset it?

**Comment by voximage** [comment]
Unsubscribe

**Comment by RRUZ** [comment]
You can restore the colors of the event log windows deleting this key from the windows registry 

> HKEY_CURRENT_USER\Software\Embarcadero\BDS\<n.0>\Debugging\Event Log Colors
