### ISSUE TITLE
Kaspersky 2016 marks your updater as malware

### ISSUE THREAD

**Issue by FunFrog-BY** [RRUZ/delphi-ide-theme-editor#111]
![clipboard02](https://cloud.githubusercontent.com/assets/9034852/20290348/9662b64a-aaf0-11e6-8e73-20ed7ae516d4.png)

**Comment by RRUZ** [comment]
Thanks very much for the report. This is false positive,  Anyway you can check the full source of the updater here https://github.com/RRUZ/delphi-ide-theme-editor/tree/master/delphi-ide-theme-editor/Updater.
