### ISSUE TITLE
How to uninstall ? 

### ISSUE THREAD

**Issue by rrezino** [RRUZ/delphi-ide-theme-editor#121]

**Comment by RRUZ** [comment]
Run the uninstaller located here _%programfiles(x86)%\The Road To Delphi\Delphi IDE Theme Editor_
or use the Windows option to uninstall Apps.

**Comment by rrezino** [comment]
But I uninstalled it but the themes and stuff were still there. 
I like it, but for some reason it's slowing down my IDE. 
Strangely, it slows down when I'm rendering lines under the last line of the file.
