### ISSUE TITLE
Support for Delphi Community Edition

### ISSUE THREAD

**Issue by AdriaanBoshoff** [RRUZ/delphi-ide-theme-editor#124]
Not sure if it's just be but this doesn't work on the Community Edition.

**Comment by checkdigits** [comment]
CE is functionally the same as XE10.2.3 from the point of view of the IDE so it should work.

**Comment by AdriaanBoshoff** [comment]
It works on Rad Studio 10.2.3 Architect but I can't seem to get it to work on the Community Edition. I've tried running as admin and etc but no luck. I'm going to try something and will update.

**Comment by AdriaanBoshoff** [comment]
I have no luck. Tried reinstalling and so on.
