### ISSUE TITLE
Add Support for Delphi 10.4 Sydney

### ISSUE THREAD

**Issue by marlonnardi** [RRUZ/delphi-ide-theme-editor#129]
Add Support for Delphi 10.4 Sydney

**Comment by AdriaanBoshoff** [comment]
I forked it and added support for 10.4 however the IDE overrides the changes in the registry when it opens.

Maybe I'm missing something?

![H9hMaG9rn6](https://user-images.githubusercontent.com/16230645/82988514-95f8b900-9ff9-11ea-82de-6124117523da.png)

**Comment by marlonnardi** [comment]
Congrats @AdriaanBoshoff  👍

**Comment by RRUZ** [comment]
I hope add support for Sydney soon.  I will post an announcement on my blog when is done.

**Comment by nalilord** [comment]
> I forked it and added support for 10.4 however the IDE overrides the changes in the registry when it opens.
> 
> Maybe I'm missing something?
> 


You have to create a new theme under "21.0\Editor\Highlight\Inbuilt Themes\\**ThemeName**", seems like the others are now hard coded into the IDE.

**Comment by AdriaanBoshoff** [comment]
> > I forked it and added support for 10.4 however the IDE overrides the changes in the registry when it opens.
> > Maybe I'm missing something?
> 
> You have to create a new theme under "21.0\Editor\Highlight\Inbuilt Themes\**ThemeName**", seems like the others are now hard coded into the IDE.

Tried this as well. IDE does not read the values and you cannot chose a theme after creating it. It seems to be easier to just manually create the theme yourself in the IDE.

**Comment by nalilord** [comment]
> Tried this as well. IDE does not read the values and you cannot chose a theme after creating it. It seems to be easier to just manually create the theme yourself in the IDE.

That's stange, for me it's working fine...

**Comment by yren66** [comment]
You will have to create all the themes under

Computer\HKEY_CURRENT_USER\Software\Embarcadero\BDS\21.0\Editor\Highlight\Custom Themes

or under:
 
Computer\HKEY_USERS\S-1-5-21-xxxxxx-yyyy-zzzzz-1111111\Software\Embarcadero\BDS\21.0\Editor\Highlight\Custom Themes

then Start Delphi 10.4 Sydney, all the registered themes would be listed at IDE under:  

Tools/Options/User Interface/Editor/Color/Color SpeedSetting dropdown, once you select one of the theme color, then the theme name would be saved at:

Computer\HKEY_CURRENT_USER\Software\Embarcadero\BDS\21.0\Editor\Options\Color SpeedSetting Key

**Comment by RRUZ** [comment]
Sydney support was added
