### ISSUE TITLE
Separate font color for active and inactive tabs!

### ISSUE THREAD

**Issue by PeterPanino** [RRUZ/delphi-ide-theme-editor#96]
IDE Tabs: There is only one font color for both active and inactive tabs:

![image](https://cloud.githubusercontent.com/assets/5140376/7882909/6fa8eed6-0612-11e5-8e5d-e28309db9e8e.png)

This causes a very bad visibility for the caption of inactive tabs:

![image](https://cloud.githubusercontent.com/assets/5140376/7882944/c876bac0-0612-11e5-8d31-123d825a9ad7.png)

So please implement a separate font color for active and inactive tabs. Thank you!

**Comment by PeterPanino** [comment]
PS: Please also implement a button "Reset to factory defaults".

**Comment by RRUZ** [comment]
You must report this on the issue page of the  https://github.com/RRUZ/Delphi-IDE-Colorizer project.
