### ISSUE TITLE
Installer references Google.Code project page

### ISSUE THREAD

**Issue by Kromster80** [RRUZ/delphi-ide-theme-editor#97]
Installer mentions Google Code page, but the Google Code is discontinued.

![image](https://cloud.githubusercontent.com/assets/4618474/8635012/01a01e76-281a-11e5-9b38-4c7898356f40.png)

**Comment by RRUZ** [comment]
Thanks, the installer was updated.

**Comment by Kromster80** [comment]
Thank you for the tool RRUZ! :-)
