### ISSUE TITLE
Delphi DITE doesn't work even "Successfully applied"

### ISSUE THREAD

**Issue by bernardopadua** [RRUZ/delphi-ide-theme-editor#98]
Delphi DITE ----
Version: 1.8.1.0
Windows: Windows 7 Professional Service Pack 1
Tool running as administrator.

The message "The theme was successfully applied" is showed to me after applying a theme.

I log all registry changes using RegFromAPP:
http://pastebin.com/88gaGmWk

Best regards.

**Comment by RRUZ** [comment]
Depending of you UAC configuration, two more confirmations are raised after of the  *successfully applied* message . You must accept both. 

![1agrme8i-uac-windows-7-pic-2-s-](https://cloud.githubusercontent.com/assets/11446959/9152250/0efd6ad6-3df7-11e5-823e-948d48958e82.png)

**Comment by bernardopadua** [comment]
Nothing appear to me.. My UAC is disables "Never notify"..
There is any other conffiguration ?

My Windows is Portguese (Brazil).. Don't know if there is something about
it...

Thanks..

2015-08-08 17:59 GMT-03:00 Rodrigo Ruz <notifications@github.com>:

> Depending of you UAC configuration, two more confirmations are raised
> after of the *successfully applied* message . You must accept both.
>
> [image: 1agrme8i-uac-windows-7-pic-2-s-]
> <https://cloud.githubusercontent.com/assets/11446959/9152250/0efd6ad6-3df7-11e5-823e-948d48958e82.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RRUZ/delphi-ide-theme-editor/issues/98#issuecomment-129044037>
> .
>



-- 
Atenciosamente,
Bernardo de P. Oliveira.
http://www.mentereversa.com

**Comment by bernardopadua** [comment]
Rodrigo.. I discover the problem.

I have two parameters on my delphi shortcurt "-abc -abc2" (not the real
paramters).. When i start my delphi with paramters, my IDE color scheme
stay the same. But when i start my delphi without it, my color SCHEME
changes.

There is something i can do to the color sheme applies with paramters ?

Thanks.

2015-08-10 11:05 GMT-03:00 Bernardo Oliveira <bernactkj@gmail.com>:

> Nothing appear to me.. My UAC is disables "Never notify"..
> There is any other conffiguration ?
>
> My Windows is Portguese (Brazil).. Don't know if there is something about
> it...
>
> Thanks..
>
> 2015-08-08 17:59 GMT-03:00 Rodrigo Ruz <notifications@github.com>:
>
>> Depending of you UAC configuration, two more confirmations are raised
>> after of the *successfully applied* message . You must accept both.
>>
>> [image: 1agrme8i-uac-windows-7-pic-2-s-]
>> <https://cloud.githubusercontent.com/assets/11446959/9152250/0efd6ad6-3df7-11e5-823e-948d48958e82.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RRUZ/delphi-ide-theme-editor/issues/98#issuecomment-129044037>
>> .
>>
>
>
>
> --
> Atenciosamente,
> Bernardo de P. Oliveira.
> http://www.mentereversa.com
>



-- 
Atenciosamente,
Bernardo de P. Oliveira.
http://www.mentereversa.com

**Comment by RRUZ** [comment]
Can you tell me which parameters(http://docwiki.embarcadero.com/RADStudio/XE8/en/IDE_Command_Line_Switches_and_Options) are you using ?

**Comment by bernardopadua** [comment]
Paramter types:
-p
-r

Parameter:
-pDelphi
-r(CompatyParamter) (not real name)

My -r is a developer default parameter of the company that i work for, uses.

2015-08-10 13:09 GMT-03:00 Rodrigo Ruz <notifications@github.com>:

> Can you tell me which parameters(
> http://docwiki.embarcadero.com/RADStudio/XE8/en/IDE_Command_Line_Switches_and_Options)
> are you using ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RRUZ/delphi-ide-theme-editor/issues/98#issuecomment-129511517>
> .
>



-- 
Atenciosamente,
Bernardo de P. Oliveira.
http://www.mentereversa.com

**Comment by bernardopadua** [comment]
I exported [HKEY_CURRENT_USER\Software\Borland\BDS\5.0\Editor\Highlight\]
and change the "BDS" to my -r parameter.
It works..

Maybe if you add some parameter on DITE to inform -r parameter name....
Don't know how would be the best solution in this case.

Thanks!

2015-08-10 13:15 GMT-03:00 Bernardo Oliveira <bernactkj@gmail.com>:

> Paramter types:
> -p
> -r
>
> Parameter:
> -pDelphi
> -r(CompatyParamter) (not real name)
>
> My -r is a developer default parameter of the company that i work for,
> uses.
>
> 2015-08-10 13:09 GMT-03:00 Rodrigo Ruz <notifications@github.com>:
>
>> Can you tell me which parameters(
>> http://docwiki.embarcadero.com/RADStudio/XE8/en/IDE_Command_Line_Switches_and_Options)
>> are you using ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RRUZ/delphi-ide-theme-editor/issues/98#issuecomment-129511517>
>> .
>>
>
>
>
> --
> Atenciosamente,
> Bernardo de P. Oliveira.
> http://www.mentereversa.com
>



-- 
Atenciosamente,
Bernardo de P. Oliveira.
http://www.mentereversa.com

**Comment by RRUZ** [comment]
the -r parameter is for use an alternative registry key for the IDE settings, for the moment the only workaround is copy manually the entries of these keys *HKEY_CURRENT_USER\Software\Borland\BDS\5.0\Editor/DITE* and *HKEY_CURRENT_USER\Software\Borland\BDS\5.0\Editor/Highlight*  to the custom key used.
