### ISSUE TITLE
Detection issue

### ISSUE THREAD

**Issue by melting-sidekick** [RRUZ/delphi-ide-theme-editor#99]
Doesn't detect Delphi 10 Seattle on Windows 10, gives the error "You don't have a Object Pascal IDE installed (1)" when loaded.

**Comment by RRUZ** [comment]
DITE detect the Installed Delphi versions using the windows registry, So check if this key exist

HKEY_CURRENT_USER)\Software\Embarcadero\BDS\17.0

Also check the value of the _App_ entry in the same key.

**Comment by melting-sidekick** [comment]
The key does exist but I do not see an App entry.

**Comment by RRUZ** [comment]
Please include  a screenshot of the key like so.

![2015-09-08 18_18_56-greenshot](https://cloud.githubusercontent.com/assets/11446959/9747811/5f71b34c-5656-11e5-851c-46dc02d3d15f.png)

**Comment by melting-sidekick** [comment]
![dxreg](https://cloud.githubusercontent.com/assets/13839963/9747867/792129b0-564e-11e5-9e25-eee44c44cb94.jpg)

**Comment by RRUZ** [comment]
Try creating a new string Value like so

![2015-09-08 18_18_56-greenshot](https://cloud.githubusercontent.com/assets/11446959/9748291/2a404716-565a-11e5-9af7-11384a7442e9.png)

Using the full path to the bds.exe file.

**Comment by melting-sidekick** [comment]
Creating the entry does fix the problem, but I wonder why entry was never there in the first place? I did a standard web install.

**Comment by RRUZ** [comment]
Maybe is related to your Delphi SKU  (Starter).

**Comment by vhanla** [comment]
I'm trying Berlin 10.1 Update 1 Starter, and I had to add that "App" string value to make it detect. 
Since many people are diving into Delphi due to its free promo editions, it could be great to fix that inconvenience for new users.

**Comment by vhanla** [comment]
RAD Studio 10.2 Tokyo Starter still needs this manual step to make it detect. 
I guess there should be a workaround detecting key "Edition" and "RootDir" to prepend it "bin\bds.exe" in order to make it detect instead of making us do it manually with "App" key.

**Comment by luebbe** [comment]
The registry key is at HKCU. Maybe you installed with a different user account and the entry got created at that users HKCU?
